[project]
name = "spice-to-sch"
version = "0.1.1"
description = "A CLI to convert SkyWater SKY130 spice files into xschem .sch files."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
[project.scripts]
spice-to-sch = "main:main"
